SELECT count(*)  FROM APPS.XX00IFAP_INVOICE_HDR_STG_ALL
WHERE 1=1 
AND CREATION_DATE BETWEEN TO_DATE('05012023', 'MMDDYYYY') AND TO_DATE('06302023', 'MMDDYYYY')
AND INVOICE_NUM LIKE 'YLP%' 
--AND STATUS <> 'PROCESSED'
--AND DESCRIPTION = 'JUN-2023  FREIGHT CHARGES -IMPORT'
--AND INVOICE_NUM = 'YLP-06-23U5'
ORDER BY CREATION_DATE DESC